version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network_inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network_inception
    depends_on:
      - mariadb

  #nginx:
    # ...

#espaço de armazenamento persistente fora do container
volumes:
  mariadb_data:
  wordpress_data:

networks:
  network_inception:
    name: network_inception
